// Typed query-key factory. Hooks only ever use this; never inline keys.
// Client staleTime stays short and uniform because the server cache does
// the heavy lifting (03 section 11). Documented choices:
//   default 60s, me Infinity (invalidated on login/switch), pulse refetches
//   on a 5 min interval, urgent 30s (optimistic writes), funnels 5 min.
export const qk = {
  me: () => ['me'] as const,
  pulse: () => ['pulse'] as const,
  kpiStrip: (person: string) => ['kpi', 'strip', person] as const,
  kpiTargets: (month: string) => ['kpi', 'targets', month] as const,
  kpiTeamSummary: (month: string) => ['kpi', 'team-summary', month] as const,
  kpiDrill: (metric: string, month: string) => ['kpi', 'drill', metric, month] as const,
  deliverables: (month: string) => ['deliverables', month] as const,
  adminUsers: () => ['admin', 'users'] as const,
  attention: (person: string) => ['attention', person] as const,
  urgent: () => ['urgent'] as const,
  blockers: () => ['blockers'] as const,
  leadsMedicalTravel: () => ['leads', 'medical-travel'] as const,
  casesSummary: () => ['cases', 'summary'] as const,
  priorities: (person: string) => ['pipeline', 'priorities', person] as const,
  pipelineHealth: () => ['pipeline', 'health'] as const,
  pipelineStaleness: () => ['pipeline', 'staleness'] as const,
  pipelineMomentum: () => ['pipeline', 'momentum'] as const,
  pipelineLosses: () => ['pipeline', 'losses'] as const,
  pipelineVelocity: () => ['pipeline', 'velocity'] as const,
  providers: () => ['pipeline', 'providers'] as const,
  handoffs: () => ['handoffs'] as const,
  appointments: () => ['appointments'] as const,
  appointmentsAnalytics: (period: string, month?: string) =>
    ['appointments', 'analytics', period, month ?? null] as const,
  crmMetrics: () => ['crm', 'metrics'] as const,
  crmFunnel: (period: string) => ['crm', 'funnel', period] as const,
  crmLeads: (page: number, status: string) => ['crm', 'leads', page, status] as const,
  crmLeadSources: (period: string, segment: string) =>
    ['crm', 'lead-sources', period, segment] as const,
  crmLeadFunnel: (period: string) => ['crm', 'lead-funnel', period] as const,
  crmPipeline: (period: string) => ['crm', 'pipeline', period] as const,
  crmJourney: () => ['crm', 'journey'] as const,
  crmSubtype: () => ['crm', 'subtype'] as const,
  crmDeals: (page: number, pipeline: string) => ['crm', 'deals', page, pipeline] as const,
  crmSegments: (metric: string) => ['crm', 'segments', metric] as const,
  financials: () => ['financials'] as const,
  financialsForecast: () => ['financials', 'forecast'] as const,
  financialsBurn: () => ['financials', 'burn'] as const,
  financialsReceivables: () => ['financials', 'receivables'] as const,
  crm: (resource: string, page: number, pageSize: number) => ['crm', resource, page, pageSize] as const,
  marketing: () => ['marketing'] as const,
  funnels: (tab: string, variant?: string, period?: string) =>
    ['funnels', tab, variant ?? '', period ?? ''] as const,
  growth: (section: string) => ['growth', section] as const,
  agents: () => ['agents'] as const,
  tasks: () => ['tasks'] as const,
  board: (tab: string, project: string, tasklist: string) =>
    ['board', tab, project, tasklist] as const,
  boardCatalog: () => ['board', 'catalog'] as const,
  boardTaskDetail: (id: string) => ['board', 'task', id] as const,
  boardAssignableUsers: () => ['board', 'assignable-users'] as const,
  socialGa4: (period: string) => ['social', 'ga4', period] as const,
  socialPlatforms: () => ['social', 'platforms'] as const,
  brief: () => ['brief'] as const,
  payoutsSummary: (cycle: string) => ['payouts', 'summary', cycle] as const,
  payoutsBookings: (cycle: string) => ['payouts', 'bookings', cycle] as const,
  payoutsRules: () => ['payouts', 'rules'] as const,
  cockpitQueue: (person: string) => ['cockpit', 'queue', person] as const,
  cockpitCase: (id: string) => ['cockpit', 'case', id] as const,
  cockpitParked: (person: string, bucket: string, page: number, pageSize: number) =>
    ['cockpit', 'parked', person, bucket, page, pageSize] as const,
  cockpitSlaPolicy: () => ['cockpit', 'sla-policy'] as const,
  providerBoard: () => ['provider-board'] as const,
  whatsappTemplates: () => ['whatsapp', 'templates'] as const,
}
